<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reports PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        h1, h2, h3, p {
            text-align: center;
        }

        table {
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table, th, td {
            border: 1px solid #333;
        }

        th, td {
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 0.9em;
            color: #666;
        }
    </style>
</head>
<body>
@php
    $now = \Carbon\Carbon::now()->timezone('Asia/Jakarta')->translatedFormat('d F Y');
@endphp
<h1>Data Report</h1>
<h3>Generated on: {{$now}} </h3>

<h2>Summary</h2>
<p>This report provides an overview of the data collected and analyzed on the given date.</p>

<h2>Data Table</h2>

<table class="table table-bordered" id="dataTable" style="min-width: max-content">
    <thead>
    <tr>
        <th>No</th>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Floor Number</th>
        <th>Message</th>
        <th>Date</th>
    </tr>
    </thead>
    <tbody>
    @php
        $no = 1;
    @endphp
    @foreach ($reports as $report)
        @php
            $date = \Carbon\Carbon::parse($report->created_at)->timezone('Asia/Jakarta')->translatedFormat('d F Y H:i:s');
        @endphp
        <tr>
            <td>{{ $no++ }}</td>
            <td>{{ $report->user->name }}</td>
            <td>{{ $report->user->email }}</td>
            <td>{{ $report->user->role }}</td>
            <td>{{ $report->floor->floor_number }}</td>
            <td>{{ $report->message }}</td>
            <td>{{ $date }}</td>
        </tr>
    @endforeach
    </tbody>
</table>
<h2>Conclusion</h2>
<p>The data provided shows a significant trend in the selected categories. Further analysis is recommended.</p>

<div class="footer">
    <p>Generated by YourCompany</p>
    <p>&copy; 2024 YourCompany. All rights reserved.</p>
</div>
</body>
</html>
